spring.application.name=citas-medicas
#Configuracion API
server.port=8078
server.servlet.context-path=/api
#Configuracion base de datos
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#Habilitacion para ejecucion de scripts(Creacion e Insercion de datos)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=embedded
spring.jpa.hibernate.ddl-auto=none
